import type { GetServerSideProps } from 'next'
import Head from 'next/head'
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import { getComics } from 'dh-marvel/services/marvel/marvel.service';
import ComicCard, { CardType } from 'dh-marvel/components/cards/home-comic-cards';
import Pagination from '@mui/material/Pagination';
import Stack from '@mui/material/Stack';
import Grid from '@mui/material/Grid';
import Box from '@mui/material/Box';
import Paper from '@mui/material/Paper';
import { styled } from '@mui/material/styles';
import { useState, useEffect, ChangeEvent } from 'react';
import { NextPageWithLayout } from './_app.page';
import type { ReactElement, ReactNode } from 'react';
import LayoutGeneral from 'dh-marvel/components/layouts/layout-general';

type Props = {
    data: CardType[],
    totalPages: number
}

const Item = styled(Paper)(({ theme }) => ({
    backgroundColor: theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
    ...theme.typography.body2,
    padding: theme.spacing(1),
    margin: theme.spacing(1)
}));

const Index: NextPageWithLayout<Props> = ({ data, totalPages }: Props) => {

    const [page, setPage] = useState<number>(1)
    const [comics, setComics] = useState<CardType[]>(data);
    useEffect(() => {
        async function getData() {
            const result = await fetch("api/comics/?page=" + page)
            const data = await result.json()
            setComics(data.results)
        }
        getData();
    }, [page])
    const hadleChange = (event: ChangeEvent<unknown>, value: number) => {
        setPage(value)
    }
    return (
        <>
            <Head>
                <title>Home Marvel Comics</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <BodySingle title={"Cómics"}>
                <Box sx={{ flexGrow: 1, display: "flex", alignItems: "center", flexDirection: "column" }}>
                    <Stack spacing={2} sx={{ marginBottom: 5 }}>
                        <Pagination
                            count={totalPages}
                            page={page}
                            color="primary"
                            onChange={hadleChange}
                        />
                    </Stack>
                    <Grid container spacing={3} sx={{ marginBottom: 5 }}>
                        {comics.map(d => {
                            return (
                                <Grid key={d.id}  >
                                    <Item >
                                        <ComicCard data={d} />
                                    </Item>
                                </Grid>)
                        })}
                    </Grid>
                    <Stack spacing={2} sx={{ marginBottom: 5 }}>
                        <Pagination
                            count={totalPages}
                            page={page}
                            color="primary"
                            onChange={hadleChange}
                        />
                    </Stack>
                </Box>
            </BodySingle>
        </>
    )
}
Index.getLayout = function getLayout(page: ReactElement) {
    return <LayoutGeneral>{page}</LayoutGeneral>
}
export const getServerSideProps: GetServerSideProps = async () => {
    const res = await getComics(0, 12);
    const totalPages = Math.ceil(res.data.total / 12);
    return {
        props: { data: res.data.results, totalPages }
    }
}
export default Index;
